#!/bin/bash

# Copyright (c) 2013 Riverbed Technology, Inc.
#
# This software is licensed under the terms and conditions of the 
# MIT License set forth at:
#   https://github.com/riverbed/flyscript/blob/master/LICENSE ("License").  
# This software is distributed "AS IS" as set forth in the License.

rm project.db
rm datacache/*
rm log*.txt
python manage.py syncdb --noinput
python config/devices.py
python config/locations.py
find config/reports -name "[0-9]*.py" | xargs -L 1 -e python
