#!/bin/bash

# Copyright (c) 2013 Riverbed Technology, Inc.
#
# This software is licensed under the terms and conditions of the 
# MIT License set forth at:
#   https://github.com/riverbed/flyscript/blob/master/LICENSE ("License").  
# This software is distributed "AS IS" as set forth in the License.

if [[ $1 == "--reset" ]]; then
    rm project.db
    rm datacache/*
    rm log*.txt
fi

python manage.py syncdb --noinput
python manage.py reload

