#!/bin/bash

# Copyright (c) 2013 Riverbed Technology, Inc.
#
# This software is licensed under the terms and conditions of the 
# MIT License set forth at:
#   https://github.com/riverbed/flyscript/blob/master/LICENSE ("License").  
# This software is distributed "AS IS" as set forth in the License.

# TODO make this a python file for cross-platform support

if [[ $1 == "--reset" ]]; then
    shift
    python manage.py reset_portal $*
else
    python manage.py reload
fi
