#!/bin/bash

# Copyright (c) 2013 Riverbed Technology, Inc.
#
# This software is licensed under the terms and conditions of the 
# MIT License set forth at:
#   https://github.com/riverbed/flyscript/blob/master/LICENSE ("License").  
# This software is distributed "AS IS" as set forth in the License.

killall -9 Python
rm project.db
rm datacache/*
rm log*.txt

PYTHONPATH=$PYTHONPATH:`pwd`
python manage.py syncdb --noinput
python config/devices.py
python config/locations.py
python config/reports/1_overall.py
python config/reports/2_profiler.py
python config/reports/3_shark.py
python config/reports/4_map.py
python manage.py runserver
#python manage.py runserver `facter ipaddress`:8000
